[package]
name = "calculator"
version = "0.1.0"
authors = ["PetrifiedPanda <bfj.koehn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
